// create the actions as CONSTANTS

export const SELECT_ROVER = 'SELECT_ROVER';
export const SELECT_PICTURE_WIDTH = 'SELECT_PICTURE_WIDTH';
export const SELECT_PICTURE_HEIGHT = 'SELECT_PICTURE_HEIGHT';
export const SELECT_SOL_DATE = 'SELECT_SOL_DATE';
export const SEARCH_BEGIN = 'SEARCH_BEGIN';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const ADD_PICTURE_TO_FAVORITES = 'ADD_PICTURE_TO_FAVORITES';